name: 定时任务
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  leancloud-touch:
    runs-on: ubuntu-latest
    steps:
    - name: 刷新
      run: |
          curl -X GET \
          -H "accept: */*" \
          -H "accept-language: zh-CN,zh;q=0.9" \
          -H "cache-control: no-cache" \
          -H "pragma: no-cache" \
          -H "priority: u=1, i" \
          -H "sec-ch-ua: \"Not(A:Brand\";v=\"99\", \"Google Chrome\";v=\"133\", \"Chromium\";v=\"133\"" \
          -H "sec-ch-ua-mobile: ?0" \
          -H "sec-ch-ua-platform: \"macOS\"" \
          -H "sec-fetch-dest: empty" \
          -H "sec-fetch-mode: cors" \
          -H "sec-fetch-site: cross-site" \
          -H "x-lc-id: ${{ secrets.LEANCLOUD_PUBLIC_ID }}" \
          -H "x-lc-key: ${{ secrets.LEANCLOUD_PUBLIC_KEY }}" \
          -H "referrer: https://frcoder-lh.github.io/" \
          -H "referrerPolicy: strict-origin-when-cross-origin" \
          "https://i2egbesf.lc-cn-n1-shared.com/1.1/classes/words?keys=-createdAt%2C-updatedAt%2C-objectId"
