name: 定时任务
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  常用单词:
    runs-on: ubuntu-latest
    steps:
    - name: 刷新
      run: |
        ls
        wget https://frcoder-lh.github.io/programer-words/me
        ls
