name: 定时任务
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: 刷新
      run: |
        ls
        wget https://words.littletools.ml/me
        ls
